Deno.serve(async (req) => {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Max-Age': '86400',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 200, headers: corsHeaders });
    }

    try {
        const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
        const supabaseUrl = Deno.env.get('SUPABASE_URL');
        const resendApiKey = Deno.env.get('RESEND_API_KEY');

        if (!serviceRoleKey || !supabaseUrl) {
            throw new Error('Configuración de Supabase faltante');
        }

        // Verificar si la generación automática está habilitada
        const configResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_config?select=*&limit=1`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        if (configResponse.ok) {
            const configs = await configResponse.json();
            if (configs && configs.length > 0 && !configs[0].auto_generation_enabled) {
                return new Response(JSON.stringify({
                    data: {
                        message: 'Generación automática deshabilitada',
                        skipped: true
                    }
                }), {
                    headers: { ...corsHeaders, 'Content-Type': 'application/json' }
                });
            }
        }

        const now = new Date();
        const firstDayOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
        const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59).toISOString();

        // Obtener contenido publicado del newsletter_content
        const contentResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_content?is_published=eq.true&published_at=gte.${firstDayOfMonth}&published_at=lte.${lastDayOfMonth}&order=created_at.asc`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let newsletterContent = [];
        if (contentResponse.ok) {
            newsletterContent = await contentResponse.json();
        }

        // Si no hay contenido específico, extraer de communiques y event_images
        let autoGeneratedContent = {
            news: [],
            events: [],
            statistics: [],
            directives: [],
            suggestions: []
        };

        if (!newsletterContent || newsletterContent.length === 0) {
            // Obtener últimos 5 comunicados
            const communiquesResponse = await fetch(
                `${supabaseUrl}/rest/v1/communiques?is_published=eq.true&order=created_at.desc&limit=5`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (communiquesResponse.ok) {
                const communiques = await communiquesResponse.json();
                autoGeneratedContent.news = communiques.map(c => ({
                    type: 'news',
                    title: c.title,
                    content: c.content.substring(0, 300) + '...',
                    image_url: c.image_url || null
                }));
            }

            // Obtener eventos de la galería
            const eventsResponse = await fetch(
                `${supabaseUrl}/rest/v1/event_images?is_active=eq.true&order=event_date.desc&limit=4`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (eventsResponse.ok) {
                const events = await eventsResponse.json();
                autoGeneratedContent.events = events.map(e => ({
                    type: 'events',
                    title: e.title,
                    content: e.description || 'Evento destacado de nuestra actividad sindical',
                    image_url: e.image_url
                }));
            }
        } else {
            // Agrupar contenido existente por tipo
            autoGeneratedContent = {
                news: newsletterContent.filter(c => c.type === 'news'),
                events: newsletterContent.filter(c => c.type === 'events'),
                statistics: newsletterContent.filter(c => c.type === 'statistics'),
                directives: newsletterContent.filter(c => c.type === 'directives'),
                suggestions: newsletterContent.filter(c => c.type === 'suggestions')
            };
        }

        // Generar HTML del newsletter
        const monthName = now.toLocaleDateString('es-ES', { month: 'long', year: 'numeric' });
        const title = `Newsletter UGT Towa - ${monthName.charAt(0).toUpperCase() + monthName.slice(1)}`;

        // Obtener QR code activo
        const qrResponse = await fetch(
            `${supabaseUrl}/rest/v1/qr_codes?is_active=eq.true&order=created_at.desc&limit=1`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let qrCode = null;
        if (qrResponse.ok) {
            const qrData = await qrResponse.json();
            if (qrData && qrData.length > 0) {
                qrCode = qrData[0];
            }
        }

        const htmlContent = generateNewsletterHTML(autoGeneratedContent, monthName, qrCode);

        // Crear estructura JSON para newsletter_editions
        const contentJson = {
            html: htmlContent,
            subject: title,
            sections: autoGeneratedContent,
            qrCode: qrCode,
            generatedAt: now.toISOString(),
            itemCount: autoGeneratedContent.news.length + autoGeneratedContent.events.length
        };

        // Verificar si ya existe un borrador para este mes
        const existingDraftResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_editions?status=eq.draft&title=eq.${encodeURIComponent(title)}`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        const existingDrafts = await existingDraftResponse.json();
        let newsletterId = null;
        let isNew = false;

        if (existingDrafts && existingDrafts.length > 0) {
            // Actualizar borrador existente
            newsletterId = existingDrafts[0].id;
            await fetch(`${supabaseUrl}/rest/v1/newsletter_editions?id=eq.${newsletterId}`, {
                method: 'PATCH',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=minimal'
                },
                body: JSON.stringify({
                    content: contentJson,
                    created_at: now.toISOString()
                })
            });
        } else {
            // Crear nuevo borrador
            isNew = true;
            const createResponse = await fetch(`${supabaseUrl}/rest/v1/newsletter_editions`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=representation'
                },
                body: JSON.stringify({
                    title,
                    content: contentJson,
                    status: 'draft',
                    auto_generated: true,
                    created_at: now.toISOString()
                })
            });

            if (!createResponse.ok) {
                const errorText = await createResponse.text();
                throw new Error(`Error creando borrador: ${errorText}`);
            }

            const newDraft = await createResponse.json();
            newsletterId = newDraft[0].id;
        }

        // Actualizar fecha de última generación
        await fetch(`${supabaseUrl}/rest/v1/newsletter_config?id=is.not.null`, {
            method: 'PATCH',
            headers: {
                'Authorization': `Bearer ${serviceRoleKey}`,
                'apikey': serviceRoleKey,
                'Content-Type': 'application/json',
                'Prefer': 'return=minimal'
            },
            body: JSON.stringify({
                last_generation_date: now.toISOString(),
                updated_at: now.toISOString()
            })
        });

        // Enviar notificación por email al administrador si hay Resend API key
        if (resendApiKey && isNew) {
            try {
                await fetch('https://api.resend.com/emails', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${resendApiKey}`,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        from: 'UGT Towa Newsletter <onboarding@resend.dev>',
                        to: ['jpedragosa@towapharmaceutical.com'],
                        subject: `[UGT Towa] Nuevo Newsletter Generado - ${title}`,
                        html: `
                            <h2>Nuevo Newsletter Generado Automáticamente</h2>
                            <p><strong>Título:</strong> ${title}</p>
                            <p><strong>Contenido incluido:</strong></p>
                            <ul>
                                <li>Noticias y comunicados: ${autoGeneratedContent.news.length} elementos</li>
                                <li>Eventos de galería: ${autoGeneratedContent.events.length} elementos</li>
                            </ul>
                            <p><strong>Estado:</strong> Borrador (pendiente de revisión)</p>
                            <p><strong>ID:</strong> ${newsletterId}</p>
                            <p>Puedes revisar y editar el newsletter en el panel de administración:</p>
                            <p><a href="${supabaseUrl.replace('supabase.co', 'space.minimax.io')}/admin/newsletter">Ir al Panel de Newsletter</a></p>
                            <hr />
                            <p style="color: #666; font-size: 12px;">Este email fue generado automáticamente por el sistema de newsletter de UGT Towa.</p>
                        `
                    })
                });
            } catch (emailError) {
                console.error('Error enviando notificación por email:', emailError);
                // No fallar la función si el email falla
            }
        }

        return new Response(JSON.stringify({
            data: {
                message: isNew ? 'Borrador creado exitosamente con contenido automático' : 'Borrador actualizado exitosamente',
                newsletterId,
                title,
                contentItems: autoGeneratedContent.news.length + autoGeneratedContent.events.length,
                autoGenerated: newsletterContent.length === 0,
                emailSent: isNew && !!resendApiKey
            }
        }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });

    } catch (error) {
        console.error('Error generando borrador:', error);

        return new Response(JSON.stringify({
            error: {
                code: 'DRAFT_GENERATION_FAILED',
                message: error.message
            }
        }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
    }
});

function generateNewsletterHTML(contentByType: any, monthName: string, qrCode: any = null): string {
    return `
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newsletter UGT Towa - ${monthName}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            background-color: #ffffff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .header {
            background-color: #e50000;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
            margin: -30px -30px 30px -30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            color: #e50000;
            font-size: 20px;
            font-weight: bold;
            border-bottom: 2px solid #e50000;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }
        .content-item {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f9f9f9;
            border-left: 4px solid #e50000;
            border-radius: 4px;
        }
        .content-item h3 {
            margin: 0 0 10px 0;
            color: #333;
            font-size: 18px;
        }
        .content-item p {
            margin: 0;
            color: #666;
        }
        .content-item img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
            border-radius: 4px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Newsletter UGT Towa</h1>
            <p>${monthName}</p>
        </div>

        ${contentByType.news.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Noticias y Comunicados</h2>
            ${contentByType.news.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                    ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" />` : ''}
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${contentByType.events.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Galería de Eventos</h2>
            ${contentByType.events.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                    ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" />` : ''}
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${qrCode ? `
        <div class="section" style="text-align: center; margin-top: 40px;">
            <h2 class="section-title">Afiliate a UGT</h2>
            <div style="display: inline-block; border: 4px solid #e50000; border-radius: 8px; padding: 20px; background-color: white;">
                <img src="${qrCode.image_url}" alt="QR de Afiliacion UGT" style="max-width: 200px; width: 100%; height: auto; margin: 0 auto; display: block;" />
                ${qrCode.description ? `<p style="margin-top: 15px; color: #666; font-size: 14px;">${qrCode.description}</p>` : ''}
            </div>
        </div>
        ` : ''}

        <div class="footer">
            <p><strong>UGT - Sección Sindical Towa Pharmaceutical Europe</strong></p>
            <p>Comprometidos con la defensa de los derechos laborales y el bienestar de todos los trabajadores</p>
            <p style="margin-top: 10px;">
                <strong>Contacto:</strong><br />
                Email: jpedragosa@towapharmaceutical.com<br />
                Dirección: Polígono Industrial, Carrer de Sant Martí, 75-97, 08107 Martorelles, Barcelona
            </p>
            <p style="margin-top: 10px; font-size: 11px; color: #999;">
                © 2025 UGT Towa Pharmaceutical Europe. Todos los derechos reservados.
            </p>
        </div>
    </div>
</body>
</html>
    `.trim();
}
