Deno.serve(async (req) => {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Max-Age': '86400',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 200, headers: corsHeaders });
    }

    try {
        const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
        const supabaseUrl = Deno.env.get('SUPABASE_URL');

        if (!serviceRoleKey || !supabaseUrl) {
            throw new Error('Configuración de Supabase faltante');
        }

        const now = new Date();
        const firstDayOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
        const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59).toISOString();

        // Obtener contenido publicado del newsletter_content
        const contentResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletter_content?is_published=eq.true&published_at=gte.${firstDayOfMonth}&published_at=lte.${lastDayOfMonth}&order=created_at.asc`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let newsletterContent = [];
        if (contentResponse.ok) {
            newsletterContent = await contentResponse.json();
        }

        // Si no hay contenido específico de newsletter, extraer de communiques y event_images
        let autoGeneratedContent = {
            news: [],
            events: [],
            statistics: [],
            directives: [],
            suggestions: []
        };

        if (!newsletterContent || newsletterContent.length === 0) {
            // Obtener últimos 5 comunicados
            const communiquesResponse = await fetch(
                `${supabaseUrl}/rest/v1/communiques?is_published=eq.true&order=created_at.desc&limit=5`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (communiquesResponse.ok) {
                const communiques = await communiquesResponse.json();
                autoGeneratedContent.news = communiques.map(c => ({
                    type: 'news',
                    title: c.title,
                    content: c.content.substring(0, 300) + '...',
                    image_url: c.image_url || null
                }));
            }

            // Obtener eventos de la galería
            const eventsResponse = await fetch(
                `${supabaseUrl}/rest/v1/event_images?is_active=eq.true&order=event_date.desc&limit=4`,
                {
                    headers: {
                        'Authorization': `Bearer ${serviceRoleKey}`,
                        'apikey': serviceRoleKey,
                    }
                }
            );

            if (eventsResponse.ok) {
                const events = await eventsResponse.json();
                autoGeneratedContent.events = events.map(e => ({
                    type: 'events',
                    title: e.title,
                    content: e.description || 'Evento destacado de nuestra actividad sindical',
                    image_url: e.image_url
                }));
            }
        } else {
            // Agrupar contenido existente por tipo
            autoGeneratedContent = {
                news: newsletterContent.filter(c => c.type === 'news'),
                events: newsletterContent.filter(c => c.type === 'events'),
                statistics: newsletterContent.filter(c => c.type === 'statistics'),
                directives: newsletterContent.filter(c => c.type === 'directives'),
                suggestions: newsletterContent.filter(c => c.type === 'suggestions')
            };
        }

        // Generar HTML del newsletter
        const monthName = now.toLocaleDateString('es-ES', { month: 'long', year: 'numeric' });
        const subject = `Newsletter UGT Towa - ${monthName.charAt(0).toUpperCase() + monthName.slice(1)}`;

        // Obtener QR code activo
        const qrResponse = await fetch(
            `${supabaseUrl}/rest/v1/qr_codes?is_active=eq.true&order=created_at.desc&limit=1`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        let qrCode = null;
        if (qrResponse.ok) {
            const qrData = await qrResponse.json();
            if (qrData && qrData.length > 0) {
                qrCode = qrData[0];
            }
        }

        const htmlContent = generateNewsletterHTML(autoGeneratedContent, monthName, qrCode);

        // Verificar si ya existe un borrador para este mes
        const existingDraftResponse = await fetch(
            `${supabaseUrl}/rest/v1/newsletters_sent?status=eq.draft&subject=eq.${encodeURIComponent(subject)}`,
            {
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                }
            }
        );

        const existingDrafts = await existingDraftResponse.json();

        if (existingDrafts && existingDrafts.length > 0) {
            // Actualizar borrador existente
            await fetch(`${supabaseUrl}/rest/v1/newsletters_sent?id=eq.${existingDrafts[0].id}`, {
                method: 'PATCH',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=minimal'
                },
                body: JSON.stringify({
                    content: htmlContent,
                    sent_at: new Date().toISOString()
                })
            });

            return new Response(JSON.stringify({
                data: {
                    message: 'Borrador actualizado exitosamente con contenido automático',
                    newsletterId: existingDrafts[0].id,
                    subject,
                    contentItems: autoGeneratedContent.news.length + autoGeneratedContent.events.length,
                    autoGenerated: newsletterContent.length === 0
                }
            }), {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' }
            });
        } else {
            // Crear nuevo borrador
            const createResponse = await fetch(`${supabaseUrl}/rest/v1/newsletters_sent`, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${serviceRoleKey}`,
                    'apikey': serviceRoleKey,
                    'Content-Type': 'application/json',
                    'Prefer': 'return=representation'
                },
                body: JSON.stringify({
                    subject,
                    content: htmlContent,
                    status: 'draft',
                    sent_at: new Date().toISOString()
                })
            });

            if (!createResponse.ok) {
                const errorText = await createResponse.text();
                throw new Error(`Error creando borrador: ${errorText}`);
            }

            const newDraft = await createResponse.json();

            return new Response(JSON.stringify({
                data: {
                    message: 'Borrador generado exitosamente con contenido automático',
                    newsletterId: newDraft[0].id,
                    subject,
                    contentItems: autoGeneratedContent.news.length + autoGeneratedContent.events.length,
                    autoGenerated: newsletterContent.length === 0
                }
            }), {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' }
            });
        }

    } catch (error) {
        console.error('Error generando borrador:', error);

        return new Response(JSON.stringify({
            error: {
                code: 'DRAFT_GENERATION_FAILED',
                message: error.message
            }
        }), {
            status: 500,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
    }
});

function generateNewsletterHTML(contentByType: any, monthName: string, qrCode: any = null): string {
    return `
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newsletter UGT Towa - ${monthName}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            background-color: #ffffff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .header {
            background-color: #e50000;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
            margin: -30px -30px 30px -30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            color: #e50000;
            font-size: 20px;
            font-weight: bold;
            border-bottom: 2px solid #e50000;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }
        .content-item {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f9f9f9;
            border-left: 4px solid #e50000;
            border-radius: 4px;
        }
        .content-item h3 {
            margin: 0 0 10px 0;
            color: #333;
            font-size: 18px;
        }
        .content-item p {
            margin: 0;
            color: #666;
        }
        .content-item img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
            border-radius: 4px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        .statistics {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }
        .stat-box {
            background-color: #e50000;
            color: white;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            margin: 10px;
            flex: 1;
            min-width: 150px;
        }
        .stat-number {
            font-size: 32px;
            font-weight: bold;
        }
        .stat-label {
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Newsletter UGT Towa</h1>
            <p>${monthName}</p>
        </div>

        ${contentByType.news.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Noticias y Comunicados</h2>
            ${contentByType.news.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                    ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" />` : ''}
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${contentByType.statistics.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Estadísticas del Mes</h2>
            <div class="statistics">
                ${contentByType.statistics.map(item => `
                    <div class="stat-box">
                        <div class="stat-number">${item.title}</div>
                        <div class="stat-label">${item.content}</div>
                    </div>
                `).join('')}
            </div>
        </div>
        ` : ''}

        ${contentByType.events.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Galería de Eventos</h2>
            ${contentByType.events.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                    ${item.image_url ? `<img src="${item.image_url}" alt="${item.title}" />` : ''}
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${contentByType.directives.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Comunicados Importantes</h2>
            ${contentByType.directives.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${contentByType.suggestions.length > 0 ? `
        <div class="section">
            <h2 class="section-title">Sugerencias Destacadas</h2>
            ${contentByType.suggestions.map(item => `
                <div class="content-item">
                    <h3>${item.title}</h3>
                    <p>${item.content}</p>
                </div>
            `).join('')}
        </div>
        ` : ''}

        ${qrCode ? `
        <div class="section" style="text-align: center; margin-top: 40px;">
            <h2 class="section-title">Afiliate a UGT</h2>
            <div style="display: inline-block; border: 4px solid #e50000; border-radius: 8px; padding: 20px; background-color: white;">
                <img src="${qrCode.image_url}" alt="QR de Afiliacion UGT" style="max-width: 200px; width: 100%; height: auto; margin: 0 auto; display: block;" />
                ${qrCode.description ? `<p style="margin-top: 15px; color: #666; font-size: 14px;">${qrCode.description}</p>` : ''}
            </div>
        </div>
        ` : ''}

        <div class="footer">
            <p><strong>UGT - Sección Sindical Towa Pharmaceutical Europe</strong></p>
            <p>Comprometidos con la defensa de los derechos laborales y el bienestar de todos los trabajadores</p>
            <p style="margin-top: 10px;">
                <strong>Contacto:</strong><br />
                Email: jpedragosa@towapharmaceutical.com<br />
                Dirección: Polígono Industrial, Carrer de Sant Martí, 75-97, 08107 Martorelles, Barcelona
            </p>
            <p style="margin-top: 10px; font-size: 11px; color: #999;">
                © 2025 UGT Towa Pharmaceutical Europe. Todos los derechos reservados.
            </p>
        </div>
    </div>
</body>
</html>
    `.trim();
}
